### ISSUE TITLE
Title is missing on some stories

### ISSUE THREAD

**Issue by Emmely2008** [HackerNews-lsd2017/hacker-news#21]
I just opened [hackernews](http://d3com7bor8tlib.cloudfront.net/) and saw lot of stories with no title.
Seems like the API returns "invalid" stories (title and url is an empty string) to the front end.

[![https://gyazo.com/cf3582774006aa77cfd4efdcce0f3818](https://i.gyazo.com/cf3582774006aa77cfd4efdcce0f3818.png)](https://gyazo.com/cf3582774006aa77cfd4efdcce0f3818)

[![https://gyazo.com/9d13e7c78c19418db16638076f11bb18](https://i.gyazo.com/9d13e7c78c19418db16638076f11bb18.png)](https://gyazo.com/9d13e7c78c19418db16638076f11bb18)

**Comment by Emmely2008** [comment]
What is the status of this issue report? Couldn't you just make sure that the API doesn't respond with "invalid" stories?

**Comment by Ldaxar** [comment]
Hi @Emmely2008 

Sorry for long response time. We were recently busy with non school life things.

This issue was due to mistake that I made that resulted in displaying comments as posts. Thats why they didn't have post title (because most of them were comments). I have resolved this issue.

Thank you for your input!
